---
all: # keys must be unique, i.e. only one 'hosts' per group
    children:   # key order does not matter, indentation does
        applications:
        locations:
            children:
                europe:
                us:
                asia:
        os:
            children:
                windows:
                redhat:
                aix:
                solaris:
        provisioner:
            children:
                azure: