---
application:
  roles:
    # type specification
    default:
      server_os: win2k16
      server_cpu: 2
      server_disk:
        - drive_letter: 'c:'
          capacity: 100
        - drive_letter: 'd:'
          capacity: 100

    front:
      server_memory: 8192

  locations:
    # type specification
    france:
      server_subnet: 192.168.1.0/24
environments:
  dev:
    roles:
      # type specification
      default:
        server_memory: 4096
    locations:
      # type specification
      france:
        server_subnet: 192.168.2.0/24
    servers:
      # type specification
      win_dev_1:
        server_location: france
        server_role: front
      win_dev_2:
        server_location: france
        server_role: back
  uat:
    servers:
      # type specification
      win_uat_1:
        server_location: france
        server_role: front
      win_uat_2:
        server_location: france
        server_role: back
        server_disk:
          - drive_letter: 'c:'
            capacity: 100
            values: error
          - drive_letter: 'd:'
            capacity: 200
