---
# -----------------------------------------------------------------------------
# Load application definition
# -----------------------------------------------------------------------------
- name: Load application definition
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    application_servers_path: '../../infrastructure/generated/{{ application }}'

  pre_tasks:
    - debug:
        msg: 'output : {{ application_servers_path }}'

  tasks:

    # -----------------------------------------------------------------------------
    # Assert playbook execution
    # -----------------------------------------------------------------------------
    - name: Assert playbook execution
      block:
        # Check mandatory variables
        - name: Check mandatory variables
          assert:
            that:
              - application_servers_selected is defined
            fail_msg: "Missing mandatory variables"

    # -----------------------------------------------------------------------------
    # Populate inventories
    # -----------------------------------------------------------------------------
    - name: Populate inventories
      block:
        - set_fact:
            inventory_all: >-
                {{ inventory_all | default({})
                  | combine( inventory, recursive=True)
                }}
          loop: '{{ application_servers_selected | dict2items }}'
          loop_control:
            label: 'Server : {{ item.key }}'

        - debug:
            var: inventory_all
            verbosity: 4

    # -----------------------------------------------------------------------------
    # write servers output structure
    # -----------------------------------------------------------------------------
    - name: write servers output structure
      block:

        # write application inventory host_vars folder
        - name: write application inventory host_vars folder
          file:
            path:  '{{ application_servers_path }}/{{ item.key }}/host_vars'
            state: 'directory'
          loop: '{{ inventory_all | dict2items }}'
          loop_control:
            label: 'Environment : {{ item.key }}'

        # Write servers hostvars
        - name: write servers
          template:
            dest: '{{ application_servers_path }}/{{ item.value.server_environment }}/host_vars/{{ item.key }}.yml'
            src:  'server_definition.yml.j2'
          loop: '{{ application_servers_selected | dict2items }}'
          loop_control:
            label: 'Server : {{ item.key }}'

        # Write Inventory
        - name: write  inventory
          template:
            dest: '{{ application_servers_path }}/{{ item.key }}/{{ application }}.yml'
            src:  'application_inventory.yml.j2'
          loop: '{{ inventory_all | dict2items }}'
          loop_control:
            label: 'Server : {{ item.key }}'
